import {
  sqliteTable,
  text,
  integer,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

/**
 * Better Auth's core schema, defined by hand rather than generated by the
 * Better Auth CLI (`npx @better-auth/cli generate`) - this repo's D1
 * migrations are produced by `drizzle-kit generate` from whatever lives
 * under schema/, the same as every other table, so keeping these tables as
 * plain Drizzle definitions here keeps that one migration pipeline the only
 * one in the project.
 *
 * Column names/types follow Better Auth's documented core schema exactly
 * (see https://better-auth.com/docs/concepts/database) so the drizzleAdapter
 * (artifacts/api-server/src/lib/betterAuth.ts) can map straight onto these
 * tables with no field-name overrides.
 *
 * `userTable.role` is GroundworkOS's own addition on top of Better Auth's
 * base `user` shape - Better Auth's `user.additionalFields` mechanism reads
 * and writes it, but expects the column to already exist in the database
 * (Better Auth does not manage schema at runtime). See
 * @workspace/shared-role for the Role type/values this column holds, and
 * lib/auth.ts (api-server) for how it's read into `c.get("_role")` once per
 * request from the session's own user row.
 */
export const userTable = sqliteTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: integer("email_verified", { mode: "boolean" })
    .notNull()
    .default(false),
  image: text("image"),
  role: text("role").notNull().default("foreman"),
  /**
   * Deactivation switch for the Settings > Users "Deactivate" action
   * (routes/admin.ts's PATCH /admin/users/:id/active) - false blocks sign-in
   * and every authenticated request (see app.ts's session middleware) while
   * leaving the account and its historical records (jobs, timesheets, audit
   * log entries referencing their name) intact. Exposed as a Better Auth
   * `user.additionalFields` entry the same way `role` is, with the same
   * `input: false` (see lib/betterAuth.ts) so a caller can never flip their
   * own switch back on through the public API.
   */
  active: integer("active", { mode: "boolean" }).notNull().default(true),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const sessionTable = sqliteTable("session", {
  id: text("id").primaryKey(),
  expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
  token: text("token").notNull().unique(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => userTable.id, { onDelete: "cascade" }),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
});

export const accountTable = sqliteTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    /**
     * "The trusted authority that issued the provider account identifier"
     * (see https://better-auth.com/docs/concepts/database#account). Added
     * in newer Better Auth releases alongside a unique (issuer, accountId)
     * pair - our installed better-auth (^1.7.2) expects this column to
     * exist, same as every other field on this table.
     */
    issuer: text("issuer").notNull().default(""),
    userId: text("user_id")
      .notNull()
      .references(() => userTable.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: integer("access_token_expires_at", {
      mode: "timestamp_ms",
    }),
    refreshTokenExpiresAt: integer("refresh_token_expires_at", {
      mode: "timestamp_ms",
    }),
    scope: text("scope"),
    password: text("password"),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
  },
  (table) => [
    uniqueIndex("account_issuer_account_id_unique").on(
      table.issuer,
      table.accountId,
    ),
  ],
);

export const verificationTable = sqliteTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
});

/**
 * GroundworkOS's own table (not part of Better Auth's schema). Backs the
 * admin-only invite flow in routes/admin.ts: an admin creates a row here
 * with a random `token`, emails a link containing it
 * (`${APP_URL}/accept-invite?token=...`), and the public
 * `POST /invitations/accept` route looks it up, creates the Better Auth
 * user server-side, stamps the invited role onto it, and marks `acceptedAt`.
 */
export const invitationsTable = sqliteTable("invitations", {
  id: text("id").primaryKey(),
  email: text("email").notNull(),
  role: text("role").notNull(),
  token: text("token").notNull().unique(),
  invitedBy: text("invited_by").references(() => userTable.id),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .notNull()
    .$defaultFn(() => new Date()),
  expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
  acceptedAt: integer("accepted_at", { mode: "timestamp_ms" }),
});

export type User = typeof userTable.$inferSelect;
export type Session = typeof sessionTable.$inferSelect;
export type Account = typeof accountTable.$inferSelect;
export type Verification = typeof verificationTable.$inferSelect;
export type Invitation = typeof invitationsTable.$inferSelect;
export type NewInvitation = typeof invitationsTable.$inferInsert;
